---
title: "CSN Image Categorization Master Results Table"
author: "Ari Dyckovsky"
output:
  md_document:
    variant: markdown_github
---

# CSN Image Categorization Master Results Table

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  strip.white = TRUE,
  tidy = TRUE,
  highlight = TRUE
)
```

## Load packages

```{r, package-loading, message=FALSE}
library(dplyr)
library(purrr)
library(tidyr)
library(stringr)
library(ggplot2)
library(hash)
library(scales)
library(readr)
```

## Set datapath and load `shlab.imgct`

Begin by setting the working directory and important top-level paths to data and 
loading necessary packages.

- NOTE: This will be changed to dynamically account for the package `shlab.imgct` via
  its GitHub instance later. For now, it is using development loading.

```{r, shlab-setup, message=FALSE}
# Set the working directory to be part of S Drive (may make dynamic later?)
# Whilst not dynamic, change for own session if mount point is not equivalent on
# local machine
shared_dir <- "~/Projects/shlab/mounts/imgct"
package_dir <- "~/Projects/shlab"

datapath <- file.path(shared_dir, "csn_images")
imgct_package_path <- file.path(package_dir, "shlab.imgct")

# Make sure that devtools, tidyverse are installed before this call
devtools::load_all(imgct_package_path)
```

```{r, load-results}
results_path <- file.path(datapath, "results")

categorizations_df <- readr::read_tsv(file.path(results_path, "categorizations.tsv"))
emotion_ratings_df <- readr::read_tsv(file.path(results_path, "general_emotion_ratings.tsv"))
```


```{r, create-and-save-master-table}
master_df <- dplyr::left_join(categorizations_df, emotion_ratings_df, by = c("image_id"))

master_df %>%
  readr::write_tsv(file.path(results_path, "master_table.tsv"),
                  append = FALSE,
                  col_names = TRUE)

knitr::kable(
  head(master_df, 5)
)
```
