---
title: "R Notebook for Validation Analysis"
output: html_notebook
---

Load pacakges

```{r}
library(ggplot2)
library(hash)
```

Constants

```{r}
COLORS <- hash()
COLORS[["BLACK"]] <- "#2F2F2F"
COLORS[["BLUE"]] <- "#0E79B2"
COLORS[["ORANGE"]] <- "#F39237"
```

Begin by setting the working directory and important top-level paths to data and 
loading necessary packages.

```{r}
# Set the working directory to be part of S Drive (may make dynamic later?)
# Whilst not dynamic, change for own session if mount point is not equivalent on
# local machine
shared_dir <- "~/Projects/shlab/mounts/imgct"
package_dir <- "~/Projects/shlab"

datapath <- file.path(shared_dir, "csn_images")
imgct_package_path <- file.path(package_dir, "shlab.imgct")

# Make sure that devtools, tidyverse are installed before this call
devtools::load_all(imgct_package_path)
```

Load the dataframe containing each participant and validation totals under the column header named `total_valid`.

```{r}
valid_df <- shlab.imgct::validate_all_participants(datapath)
```

Plot the distribution of validation counts across participants.

```{r}
ggplot(valid_df, aes(x=total_valid)) + 
  geom_histogram(binwidth=1, color=COLORS[["BLACK"]], fill=COLORS[["BLUE"]])
```



